name: flutter_weather_demo
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  flutter_command: ^2.0.0 
  get_it: ^6.0.0
  get_it_hooks:
    path: ../
  functional_listener: ^2.0.0

flutter:
  uses-material-design: true
